### PR TITLE
Hotfix 2.5.4

### PR DESCRIPTION
**Pull request by valendesigns**
- [x] Fix the select field value visibility. #496
- [x] OptionTree and Visual Composer - get_custom_field stripped with Frontend Editor #375
- [x] Support term splitting in WordPress 4.2 #499
- [x] Escape `add_query_arg` to protect against possible XSS injection.
- [x] i18n
- [ ] Update OptionTree Theme

### CODE REVIEW

**Comment by valendesigns** [comment]
I've already spent 8 hours today on OptionTree and I'm running out of steam. I would like to have support for term splitting already done, but it's not a straight forward fix. I need to think on it more. This release will have to wait until tomorrow unless someone wants to help me with it and has some ideas to share. In any case term splitting needs to be supported before WordPress 4.2 comes out later this week. So help is appreciated.

Cheers,
Derek

**Comment by valendesigns** [comment]
Hey Guys,

Please test this hotfix version as there are some important updates in it. I stayed up all night to make it work. I'm going to go pass out and will release it when I wake up.

Thank You!

**Comment by BassemN** [comment]
Hi @valendesigns 
- [x] Fix Select Option Value Changes. :+1: 
- [x] OptionTree and Visual Composer - get_custom_field stripped with Frontend Editor.  :+1: 

How can we test term splitting?

**Comment by valendesigns** [comment]
@BassemN I posted some code in the term splitting ticket that will help.

**Comment by valendesigns** [comment]
So 2.5.4 is done, I'm just updating the OptionTree Theme with a version bump and then will release everything in a few minutes.

**Pull request merged**
