### PR TITLE
Dynamic CSS with Wordpress Multisite

### PR DESCRIPTION
**Pull request by valendesigns**
This PR is in reference to: Dynamic CSS with Wordpress Multisite #356

### CODE REVIEW

**Comment by valendesigns** [comment]
@CapitalH I need someone to test this before it goes into 2.5.0. Are you available?

**Comment by BassemN** [comment]
@valendesigns If I save the "Theme Options" on any website on the network, they all write into the same dynamic.css file which causes conflict between all websites.

**Comment by valendesigns** [comment]
Yes, but do they still when you filter the dynamic.css file path like so.
```PHP
if ( ! function_exists( 'filter_css_option_file_path' ) ) {
    function filter_css_option_file_path( $filepath ) {
        if ( is_multisite() ) {
          $filepath = get_stylesheet_directory() . '/dynamic-' . get_current_blog_id() . '.css';
        }
        return $filepath;
    }
}
add_filter( 'css_option_file_path', 'filter_css_option_file_path' );
```

**Comment by BassemN** [comment]
@valendesigns  Yes, it is working now using the filter, but I think it should be filtered on the multisite automatically. What do you think? also is there any way to create the file automatically without the need to create it for each new website on the network?

**Comment by valendesigns** [comment]
No. Not the way the current code works and is why we can't make it automatic just yet. There definitely needs to be some multisite changes that need to be made but it's to early to force this setup until more work happens on the branch that changes how the dynamic.css file is created and saved. But that's at a standstill until I figure out how the CSS option type gets saved for meta boxes. Once that gets solved we can roll out a multisite automagic fix.

**Comment by BassemN** [comment]
Great, for now it is working well with the filter and you can merge it to 2.5.0 branch.

**Comment by valendesigns** [comment]
@BassemN Can you also verify that the options values are specific to that blog and the contents of dynamic.css are not leaking into each other.

**Comment by BassemN** [comment]
@valendesigns I have triple check it on three websites on the network and each website has its dynamic css file and there is no leaking between blogs.

**Comment by valendesigns** [comment]
@BassemN Awesome! Thank you. Is there a scenario that you can think of where changing the URL structure now would break a working network worse than it already is? Or is the current implementation utterly broken, and us forcing this new multisite URL structure doesn't mean creating a new regression?

**Comment by CapitalH** [comment]
@valendesigns It's seems like I have missed all the good parts of testing. (Different time zones)

Anyways, I hope I can still be useful. I will also give it a try and will get back to you ASAP.

**Comment by valendesigns** [comment]
@CapitalH Yes please do, the more the better! We need to solve this before I go to sleep tonight. It's the last issue left for the 2.5.0 release. You can probably answer my last question regarding the current implementation and if there is a working scenario, as well.

**Comment by CapitalH** [comment]
@valendesigns  Yes it works flawlessly on my local multisite
Now none of the sites in my network are queueing dynamic.css file (and I don't think they are supposed to) and now each site based on it's id queues and writes to it's own dynamic.css file (in my case dynamic-1.css and dynamic-2.css)

Regarding the current implementation I don't think it's gonna break anything since it's id based and naturally OT does not queue the file if it does not exist so we are safe here.

About the working scenario, in my case this is just what I need since my purpose is theme demos and this works just fine for me. 

But about other cases maybe @BassemN 's case might need an automatic system (if I understood him well) But for your information I the other day I was searching the web for another Custom CSS solution to get it work on multisite and in many forums this plugin was recommended
https://wordpress.org/plugins/my-custom-css/ and they all claimed that it works on a network. So maybe you could give it a look and see if there is anything in that plugin that you could add to OT (or for future reference maybe)

**Comment by valendesigns** [comment]
@CapitalH Thank you for the plugin suggestion, though it only prints styles to the head. So it's not really applicable in our case.

When using OT 2.4.6 and someone activates a theme network wide it writes over the dynamic.css anytime someone updates their blog. However, does it also do this if each blog uploads it's own version of the theme or is that even possible?

**Comment by CapitalH** [comment]
@valendesigns I'm not sure if I got your point, but I'm using OT in theme mode, and I'm adding the filter you provided to my theme's functions.php so I guess if anyone adds another theme the same filter should be added to their functions.php and if they don't as you mentioned OT will write to the default dynamic.css file.

**Comment by valendesigns** [comment]
I'm just trying figure out if I change the URL structure so no filter is needed, if that could possible break an already working blog in multisite. Or if there really isn't a scenario where `dynamic.css` works currently.

**Comment by BassemN** [comment]
@valendesigns @CapitalH  I think we should force all multisite to use the new implementation without the need to use the filter as the current situation considered as a bug. and to prevent any breaks that may come from 2.4.6 version we can add a condition to check if the current blog has a specific dynamic CSS file (EX. dynamic-1.css) then load it, if not load the dynamic.css file

**Comment by CapitalH** [comment]
@BassemN I agree, I think it's the best way to prevent future bugs. And I guess right now OT detects if a certain file exists and then enqueues it, but as you said this functionality should be extended to support the current multisite situation too.

**Comment by valendesigns** [comment]
Other than a theme being installed once on a network, and no other themes using `dynamic.css`, I can't think of another situation where `dynamic.css` would actually work in 2.4.6 or below on multisite. But how to account for a single install in the code is not really clear.

**Comment by valendesigns** [comment]
I think I got it.

If I change:
```PHP
$filepath = get_stylesheet_directory() . '/dynamic.css';
```
to:
```PHP
$filepath = get_stylesheet_directory() . '/dynamic.css';
if ( is_multisite() ) {
  $multisite_filepath = get_stylesheet_directory() . '/dynamic-' . get_current_blog_id() . '.css';
  if ( file_exists( $multisite_filepath ) ) {
    $filepath = $multisite_filepath;
  }
}}
```

Then we do not replace `dynamic.css` without the file existing and current sites continue working.

And change:
```PHP
/* grab a copy of the paths array */
if ( is_multisite() ) {
  $ot_css_file_paths = get_blog_option( get_current_blog_id(), 'ot_css_file_paths', array() );
} else {
  $ot_css_file_paths = get_option( 'ot_css_file_paths', array() );
}
```
to:
```PHP
/* grab a copy of the paths array */
$ot_css_file_paths = get_option( 'ot_css_file_paths', array() );
if ( is_multisite() ) {
  $ot_css_file_paths = get_blog_option( get_current_blog_id(), 'ot_css_file_paths', $ot_css_file_paths );
}
```

Then the `get_option` version is used as the default value for `get_blog_option` and the previous paths migrate and everything starts working right once people create the `dynamic-{current-blog-id}.css`. Which needs to be documented somewhere.

**Comment by CapitalH** [comment]
@valendesigns Seems practical
I hope to see it soon in 2.5

**Comment by valendesigns** [comment]
Please test the latest changes and don't forget to remove the custom filter we added.

**Comment by CapitalH** [comment]
@valendesigns 

Works like a charm.

Here is how I tested it:
First I created dynamic-1.css and dynamic-2.css while dynamic.css still existed. It worked as expected, each site wrote to it's own dynamic.css file.

Then I deleted the dynami-1 and dynamic-2 files and resaved the options, this time it changed for the whole network, meaning that the options were written to dynamic.css file.

Is there any other case scenarios you want me to test it on?

**Comment by BassemN** [comment]
I got the same results like @CapitalH got.

**Comment by valendesigns** [comment]
Then we agree it's fixed and not adding new bugs.

**Comment by CapitalH** [comment]
@valendesigns That is true.

**Comment by BassemN** [comment]
@valendesigns yes, it is fixed.

**Comment by CapitalH** [comment]
@valendesigns  For documentation purpose:

For none developers I think the best way to dynamically get their blog id and create dynamic-{{id}}.css file would be by adding a body class to their site, they can just add the following to their functions.php file and then by looking at their site source code they can get the id and create the files accordingly:

```php
function my_body_classes( $classes ) {
	if ( is_multisite() ) {
		$classes[] = 'multisite-id-is-'.get_current_blog_id();
	}

	return $classes;
}
add_filter( 'body_class', 'my_body_classes' );
```

**Comment by kekkster** [comment]
I can´t get it to work. I have updated OT to 2.5.1 but I still have problems with my network (one site change changes all other sites).
What theme files do I need to modify in order to get it to work?

My problem (that I noticed doesn´t work) is that, when I change font for the menu for Site1 in Theme Options, it resets the font for Site2 and Site3. It shows the correct font for Site1. 
If I change font for Site 2, it resets the font for Site1 and Site3 but show correct font for Site 2... etc. etc.

Please help! Thanks in advance!

**Comment by CapitalH** [comment]
@kekkster did you create site specific dynamic-{{site-ID}}.css files?

Add the function in the the previous comment to the functions.php file of your theme and after that in the body classes of each of your sites you can see the ID of that site.
Now for each site you need a separate dynamic css files ending with the ID of that site. For me it's just dynamic-1.css dynamic-2.css and dynamic-3.css because I currently have three sites in my network and if I add the fourth one and it's ID happen to be 4 then I'd add another file and call it dynamic-4.css

It's working flawlessly for me.

**Comment by kekkster** [comment]
@CapitalH Thanks for your reply!
No, haven´t created additional dynamic.css-files, should I just add them to the theme root?
Testing now!

**Comment by CapitalH** [comment]
@kekkster Exactly. Just added them exactly like you add dynamic.css file but one file for each site. The sites that do not have a dynamic css file will automatically write to the default dynamic.css file if it exists

**Comment by kekkster** [comment]
@CapitalH Brilliant! It works perfectly! Big thanks! :)
However... the files (dynamic-1.css, dynamic-2.css etc.) doesn´t change. Weird! I see the changes on the different demo sites and in the different theme options panels, but not in the css-files. Odd.. but it works! :)

**Comment by valendesigns** [comment]
If the contents of file are not updating then the permissions are not correct for the server to write to it.

**Comment by kekkster** [comment]
@valendesigns Yeah, weird that it works anyway. What permissions should the files have?
When I look at the source code it points to this file (example) "dynamic-4.css?ver=2.5.1". Not "dynamic-4.css".

**Pull request merged**
