### PR TITLE
Feature: OT Widgets

### PR DESCRIPTION
**Pull request by RistoNiinemets**
Some work in progress, but it definitely is worth it. Needs some workaround for saving list-item kind of types and some other types.

All types (checked means they're OK, at least I think so):
- [x] background
- [x] category-checkbox
- [x] category-select
- [x] checkbox
- [x] colorpicker
- [ ] css
- [x] custom-post-type-checkbox
- [x] custom-post-type-select
- [x] date-picker
- [x] date-time-picker
- [x] gallery
- [ ] list-item
- [x] measurement
- [x] numeric-slider
- [x] on-off
- [x] page-checkbox
- [x] page-select
- [x] post-checkbox
- [x] post-select
- [x] radio
- [x] radio-image
- [x] select
- [x] sidebar-select
- [ ] slider
- [ ] social-links
- [ ] tab
- [x] tag-checkbox
- [x] tag-select
- [ ] taxonomy-checkbox
- [ ] taxonomy-select
- [x] text
- [ ] textarea
- [x] textarea-simple
- [ ] textblock
- [ ] textblock-titled
- [x] typography
- [x] upload

An example widget for testing out all the types:

``` php
class OT_First_Widget extends OT_Widget {
    function __construct() {
        $this->id          = 'ot_first_widget';
        $this->name        = 'OT First Widget Ever';
        $this->description = 'first widget ever';

    $all_types         = array(
      'background'                => __('Background', 'ot-widgets'),
      'category-checkbox'         => __('Category Checkbox', 'ot-widgets'),
      'category-select'           => __('Category Select', 'ot-widgets'),
      'checkbox'                  => __('Checkbox', 'ot-widgets'),
      'colorpicker'               => __('Color Picker', 'ot-widgets'),
      'css'                       => __('CSS', 'ot-widgets'),
      'custom-post-type-checkbox' => __('Custom Post Type Checkbox', 'ot-widgets'),
      'custom-post-type-select'   => __('Custom Post Type Select', 'ot-widgets'),
      'date-picker'               => __('Date Picker', 'ot-widgets'),
      'date-time-picker'          => __('Date Time Picker', 'ot-widgets'),
      'gallery'                   => __('Gallery', 'ot-widgets'),
      'list-item'                 => __('List Item', 'ot-widgets'),
      'measurement'               => __('Measurement', 'ot-widgets'),
      'numeric-slider'            => __('Numeric Slider', 'ot-widgets'),
      'on-off'                    => __('On/Off', 'ot-widgets'),
      'page-checkbox'             => __('Page Checkbox', 'ot-widgets'),
      'page-select'               => __('Page Select', 'ot-widgets'),
      'post-checkbox'             => __('Post Checkbox', 'ot-widgets'),
      'post-select'               => __('Post Select', 'ot-widgets'),
      'radio'                     => __('Radio', 'ot-widgets'),
      'radio-image'               => __('Radio Image', 'ot-widgets'),
      'select'                    => __('Select', 'ot-widgets'),
      'sidebar-select'            => __('Sidebar Select',  'ot-widgets'),
      'slider'                    => __('Slider', 'ot-widgets'),
      'social-links'              => __('Social Links', 'ot-widgets'),
      'tab'                       => __('Tab', 'ot-widgets'),
      'tag-checkbox'              => __('Tag Checkbox', 'ot-widgets'),
      'tag-select'                => __('Tag Select', 'ot-widgets'),
      'taxonomy-checkbox'         => __('Taxonomy Checkbox', 'ot-widgets'),
      'taxonomy-select'           => __('Taxonomy Select', 'ot-widgets'),
      'text'                      => __('Text', 'ot-widgets'),
      'textarea'                  => __('Textarea', 'ot-widgets'),
      'textarea-simple'           => __('Textarea Simple', 'ot-widgets'),
      'textblock'                 => __('Textblock', 'ot-widgets'),
      'textblock-titled'          => __('Textblock Titled', 'ot-widgets'),
      'typography'                => __('Typography', 'ot-widgets'),
      'upload'                    => __('Upload', 'ot-widgets')
    );

    foreach( $all_types as $type => $name ) {
      $this->fields[] = array(
        'label'       => $name,
        'id'          => 'type_' . $type,
        'type'        => $type,
      );
    }

        parent::__construct();
    }

    public function widget( $args, $instance ) {
        print_r($instance);
    }
}

if( function_exists( 'ot_register_widget' ) ) {
  ot_register_widget( 'OT_First_Widget' );
}

```

### CODE REVIEW

**Comment by BassemN** [comment]
@RistoNiinemets Keep up the good work

**Comment by Chovanec** [comment]
this is great news, hope 2.6.0 will be released soon

**Comment by BassemN** [comment]
@RistoNiinemets Hello dear,
Derek created 2.6.0 branch so it is a good time to finish this PR so he can merge it on the new release :)
Thanks

**Comment by valendesigns** [comment]
I doubt it will be ready in time. It would need to be finished and tested before merged. Also I'm hesitant to add any large features until I can add unit tests and do a full code & security review of the current ones. This plugin needs to be modernized pretty badly and brought up to my current standards. It requires an overhaul. I'll work out a roadmap and discuss it with Collis.

**Pull request closed without merging**
