### PR TITLE
deprecated create_function to function() ; notification from "Query Monitor" 

### PR DESCRIPTION
**Pull request by modesthatred**
Hi, I'm a beginner developer, but I would like to help. I fixed the errors that "Query Monitor" showed me, maybe it will be useful. 
WP 4.9.7 
PHP7.2 and PHP 5.5

Small update

### CODE REVIEW

**Comment by wp-organic** [comment]
Hello Valendesigns,

I would like to inform you that newer version of PHP 7.2+ issue create for your plugin.

PHP Warning
--------------
Deprecated: Function create_function() is deprecated in /homepages/8/...FACK_PATH.../wp-content/plugins/option-tree/includes/ot-functions-admin.php on line 69

Just read about PHP create_function through reference link say : http://php.net/manual/en/function.create-function.php

This function has been DEPRECATED as of PHP 7.2.0. Relying on this function is highly discouraged.

Please fix this issue and update newer version of plugin on https://wordpress.org/plugins/option-tree/

Thanks in advance.

**Comment by tomperys** [comment]
I have also the error on my site with php 7.2 (Function create_function() is deprecated ). As I can see it was reported a few months ago. Is there a fix already?

**Comment by barthubbard** [comment]
+1

**Comment by ImperatoDavide** [comment]
1+

**Comment by tonymartin-dev** [comment]
Hi! I had this problem and, after some googling, I found a solution that seems to work. 

I just went to the line 69 of wp-content/plugins/option-tree/includes/ot-functions-admin.php (as the error indicated) and changed the current code:

`add_filter( 'option_page_capability_' . ot_options_id(), create_function( '$caps', "return '$caps';" ), 999 );`

to

`add_filter( 
        'option_page_capability_' . ot_options_id(), 
        function($caps){return '$caps';},
        999 
);`

I just turned the deprecated "create_function()" into an anonymous function. If somebody has a better solution or see some error in mine, I'd love to hear about it ! :-)

**Comment by valendesigns** [comment]
I've fixed this already in the `develop` branch I'm pushing up soon. However, I did it differently because `$caps` is a variable set above not a parameter passed to the function. The function is meant to return the capability for the page, which we set above in a filter. The code ended up like this.
```
add_filter(
	'option_page_capability_' . ot_options_id(),
	function() use ( $caps ) {
		return $caps;
	},
	999
);
```
Version 2.7.0, coming soon, requires PHP 5.3+, but it's a small price to pay for an updated version of the plugin. Thank you for creating this PR and sorry I hadn't looked at it. I've not really payed attention to the notifications here for a long time. I'll close this PR once the `develop` branch has been pushed up.

**Comment by valendesigns** [comment]
Fixed in #695

**Comment by Jany-M** [comment]
Please @valendesigns could you release v2.7?
Still dont see it [here](https://github.com/valendesigns/option-tree/releases).

**Pull request closed without merging**
