### PR TITLE
Feature: WP_Customize

### PR DESCRIPTION
**Pull request by valendesigns**
Hi Derek, 

I'm a ThemeForest author just starting to sell WP Themes. After looking through other options framework, I found out that OptionTree is the best looking options framework with the cleanest code!

However I'm using OptionTree along with WP_Customize, and this leads to confusion while getting the options through the theme. Some options are from WP_Customize and some are from OptionTree.

FYI, I'm separating the options that doesn't have anything to do with the looks of the theme into OptionTree, or WP_Customize otherwise.

Is there any way to make OptionTree able to read the options defined by WP_Customize?
I've already tried putting the WP_Customize results in the option_tree field, but upon saving OptionTree overrides the whole options.

Do you think it's a good idea to make OptionTree only updates the option being saved, like in the WP_Customize API? I digged through wp-includes/class-wp-customize-manager.php and this is not that hard to implement.

OptionTree doesn't have to know anything about the options added by WP_Customize, but it should be able to read it in other words.

Thanks!

### CODE REVIEW

**Comment by BassemN** [comment]
Hi Derek. Why you closed this pull :( ?

**Comment by valendesigns** [comment]
This pull request automatically closed when I deleted the 2.5.0 branch. And the `feature-WP_Customize` branch itself had no commits so I removed it as it was not up to date. I'll be creating a new branch for 2.6.0 based on the latest version of OT.

**Comment by BassemN** [comment]
Thank you Derek for all your hard work. We really appreciate it.

**Comment by valendesigns** [comment]
Yeah, no worries. I don't really use OT much anymore but will keep developing it. Most of my time is spent contributing to the WordPress Core these days. I plan on trying to build out some customizer controls and integrating build tools and PHPUnit into 2.6.0, just need to find some time this month to get it done. Cheers!

**Pull request closed without merging**
