### PR TITLE
Fix zero value issue for certain option types

### PR DESCRIPTION
**Pull request by BassemN**
Fix zero value for border option type
Fix zero value for box shadow option type
Fix zero value for dimension option type
Fix zero value for measurement option type
Fix zero value for spacing option type

### CODE REVIEW

**Comment by valendesigns** [comment]
I'll take a look at this either late tonight or tomorrow morning and release hotfix-2.5.5 though looking at it real quick looks like it should work well. Thanks for the PR and for correcting the branch!

**Comment by BassemN** [comment]
It's my pleasure to contribute into this awesome plugin :)

**Comment by BassemN** [comment]
Hi @valendesigns when will you release the hotfix?

**Comment by valendesigns** [comment]
I'll release it tomorrow afternoon. I got really busy the last two days. Sorry!

**Comment by valendesigns** [comment]
This has been merged into PR #515 for the hotfix-2.5.5 branch.

**Pull request closed without merging**
