### PR TITLE
OptionTree version 2.7.0

### PR DESCRIPTION
**Pull request by valendesigns**

### CODE REVIEW

**Comment by Jany-M** [comment]
Do you think you could release `v2.7`?
Still dont see it [here](https://github.com/valendesigns/option-tree/releases).

**Comment by jxs714** [comment]
> _No description provided._

Hey bud,

Thanks for keeping this plugin alive! Any download available yet? Several are patiently waiting for your updated version. :)

**Comment by valendesigns** [comment]
You can test the develop branch https://github.com/valendesigns/option-tree/archive/develop.zip

**Comment by valendesigns** [comment]
Also, I cannot cut a new release until the plugin has gone through review on wordpress.org, there may be changes required. I don't expect there to be but anything is possible.

**Comment by ryanlabelle** [comment]
I did some testing, no errors to report, just some minor styling. I created a pull request here: 

https://github.com/valendesigns/option-tree/pull/698

Thanks for updating and preparing this for PHP 7.2 🥇

**Comment by valendesigns** [comment]
Hi everyone, sorry for the delay in getting this released I was AFK for a bit. However, I'm going to do some last minute clean up and push it up to .ORG today. If there is anything that needs to be fixed this morning is the last chance to get it into the next version.

**Comment by ryanlabelle** [comment]
Thanks again @valendesigns

**Comment by BassemN** [comment]
@valendesigns no sorry man and thanks for the amazing update :+1:

**Comment by Jany-M** [comment]
Thank you @valendesigns !!!

**Comment by valendesigns** [comment]
Merged and deployed to .org, we'll see how long it takes to get approved and available for download again.

**Pull request merged**
