### PR TITLE
Feature: Google Fonts

### PR DESCRIPTION
**Pull request by valendesigns**
- [x] Merge & Test Google Fonts Option Type #364
- [x] Make field repeatable so you can load multiple fonts at once.
- [x] Filter typography option to include saved Google Fonts
- [x] Verify Google fonts display correctly in dynamic CSS output
- [x] Auto enqueue Google Fonts stylesheet
- [x] Validate on save
- [x] Update `readme.txt`
- [x] Create a dedicated Google Web Fonts API key
- [x] Add option type to docs page
- [x] Update `.po`
- [x] Update `option-tree-theme` [#8](https://github.com/valendesigns/option-tree-theme/pull/8)
- [x] Add subsets to the end of the Google Fonts URL.

### CODE REVIEW

**Comment by valendesigns** [comment]
Hello Everyone, 

The Google Fonts branch needs to be tested ASAP! Please download or checkout the branch and test that it's working for you as expected, and that it's clear how to use it. You can find a demo of this option type in the `option-tree-theme` PR [#8](https://github.com/valendesigns/option-tree-theme/pull/8).

**Comment by BassemN** [comment]
@valendesigns 
I'll test it and feed you back

**Comment by valendesigns** [comment]
@BassemN Awesome! Just made a quick change to the enqueue order for the css so it loads before the main stylesheet so you may need to refresh your code.

**Comment by BassemN** [comment]
There is something wrong with the font family names which consist from two words or more. I added "Indie Flower" font then I chose it  for a typography option, the returned font family name is "indieflower" which is not working and it should be "Indie Flower"

**Comment by valendesigns** [comment]
There is nothing wrong. It saves the font families as array key safe strings to query against. You are never meant to output the key. Why are you seeing the key, and in what context? The option type does everything for you. Why do you need the contents of the saved array?

**Comment by BassemN** [comment]
I'm using a PHP function to parse the typography option like below
```php
function get_typography_value($typo_setting) {
	$typo_setting = ot_get_option($typo_setting, array());
	$style = '';

	if (!empty($typo_setting['font-color']))
		$style .= 'color: ' . $typo_setting['font-color'] . ';';
	if (!empty($typo_setting['font-family']))
		$style .= 'font-family: "' . $typo_setting['font-family'] . '";';
	if (!empty($typo_setting['font-size']))
		$style .= 'font-size: ' . $typo_setting['font-size'] . ';';
	if (!empty($typo_setting['font-style']))
		$style .= 'font-style: ' . $typo_setting['font-style'] . ';';
	if (!empty($typo_setting['font-variant']))
		$style .= 'font-variant: ' . $typo_setting['font-variant'] . ';';
	if (!empty($typo_setting['font-weight']))
		$style .= 'font-weight: ' . $typo_setting['font-weight'] . ';';
	if (!empty($typo_setting['letter-spacing']))
		$style .= 'letter-spacing: ' . $typo_setting['letter-spacing'] . ';';
	if (!empty($typo_setting['line-height']))
		$style .= 'line-height: ' . $typo_setting['line-height'] . ';';
	if (!empty($typo_setting['text-decoration']))
		$style .= 'text-decoration: ' . $typo_setting['text-decoration'] . ';';
	if (!empty($typo_setting['text-transform']))
		$style .= 'text-transform: ' . $typo_setting['text-transform'] . ';';

	return $style;
}
```
in this case Google fonts don't work.

**Comment by BassemN** [comment]
I noticed that when I load "Open Sans" & "Abel" Google fonts like below image
theme options worpress blog wordpress

the generated stylesheet link is http://fonts.googleapis.com/css?family=Open+Sans:300,italic&subset=devanagari|Abel:regular which is gives 404 error but If I load "Abel" then "Open Sans" like the below image 
theme options worpress blog wordpress-1
the generated stylesheet link is http://fonts.googleapis.com/css?family=Abel:regular|Open+Sans:300,italic&subset=devanagari which is working

**Comment by valendesigns** [comment]
@BassemN I believe this will work for you.

```PHP
if ( ! empty( $typo_setting['font-family'] ) ) {
  $ot_google_fonts = get_theme_mod( 'ot_google_fonts', array() );
  if ( isset( $ot_google_fonts[$typo_setting['font-family']]['family'] ) ) {
    $style .= 'font-family: "' . $ot_google_fonts[$typo_setting['font-family']]['family'] . '";';
  } else {
    $style .= 'font-family: "' . $typo_setting['font-family'] . '";';
  }
}
```

**Comment by valendesigns** [comment]
@BassemN Open Sans doesn't have that variant, nor does Abel. It seems to me there is an error in the API response as it should never give you the `devanagari` option in the first pace.

**Comment by BassemN** [comment]
@valendesigns your PHP code works well for me.

**Comment by maimairel** [comment]
@valendesigns Thanks for making my PR official :)

About the issue mentioned by @BasseemN, Google fonts does not accept `&subset=` in the middle of the query, it should be always at the end of the query string.

**Comment by valendesigns** [comment]
I'll fix it so the subset always comes at the end.

**Comment by valendesigns** [comment]
Fixed the subset issue.

**Comment by valendesigns** [comment]
@BassemN I'm curious to know how you're getting the font family label value to work with your custom parser for other fonts? They all save as the array key values. Only the CSS option type converts them to their labels and prints them out. I guess it's working because they're probably not case sensitive, so it appears to be fully functioning how you have it setup.

Anyhow, I'm merging this feature into 2.5.0 and any further testing and/or updates can continue there.

**Pull request merged**
