### PR TITLE
Release: 2.5.0

### PR DESCRIPTION
**Pull request by valendesigns**
Issue tracker for 2.5.0

- [x] Feature: Option Types #411
- [x] Theme-check issue with ot_create_media_post() function #427
- [x] Icon font in Section and Tab labels #422
- [x] CSS Bug and rendering issue after activating "WP Review" Plugin #413
- [x] Google Fonts Option Type #444
- [x] Fix icons that are not aligned correctly
- [x] Feature: Filter On/Off Switch #447
- [x] Dynamically added slider in list item "on change trigger" #440
- [x] Estonian translation #370 via the Google Fonts branch
- [x] I have to load the options page twice after editing them #346
- [x] Dynamic CSS with Wordpress Multisite #449
- [x] Add readonly to datepicker #373
- [x] Theme options as a parent menu #355
- [x] Remove CleanUp Message #446
- [x] Delete all merged branches
- [x] Upload option removed %20 from external url #386
- [x] Javascript Option Type #416
- [x] Move local dev into WordPress core src plugins directory & test 4.2-alpha.
- [x] Final i18n file update
- [x] Update stable tag

### CODE REVIEW

**Comment by valendesigns** [comment]
This will likely be out next week. However, I didn't have the time this month to do the Customizer ticket. So it will not be included. I'll do what I can to fix the permission issue and I've got a local branch with the Google font option type almost done.

**Comment by anteksiler** [comment]
@valendesigns Will you add the Google Fonts option type?

**Comment by valendesigns** [comment]
Yes, the Google Fonts branch I'm working on locally is almost done. I just need to clean it up and get some feedback before it goes into 2.5 which I'll do in the next couple of days.

**Comment by satrya** [comment]
Thank you @valendesigns

**Comment by jetonr** [comment]
Thank you @valendesigns can't wait to test 2.5.0!

**Comment by ifkas** [comment]
Hey there, me neither, I can't wait too :)

**Comment by valendesigns** [comment]
2.5.0 will go live on Monday. I'll finish the last few bits over the weekend. However, in the meantime feel free to test the branch and give feedback while I still have time still to fix it. Thanks Guys!

**Comment by BassemN** [comment]
I'll start testing the 2.5.0 branch now.

**Comment by BassemN** [comment]
@valendesigns I'm still seeing the "OptionTree Cleanup" page although I have nothing to clean up. Is this behavior is normal?

**Comment by valendesigns** [comment]
@BassemN That seems unlikely. Are you sure you have the most recent updates? The page is only viewable if you have something to clean up. Do you still see a navigation menu item under appearance or just the admin nag?

**Comment by BassemN** [comment]
@valendesigns I cleared the cache and the page disappeared. sorry for this.

**Comment by valendesigns** [comment]
No worries!

**Comment by vburlak** [comment]
@valendesigns i think we are all very excited :+1:

**Comment by valendesigns** [comment]
Hey Guys,

Just some i18n stuff left to do and 2.5.0 is complete. Well, if there's no bugs to reports in the next 24 hours. Which means... Please test all the new features as much as you can today! This goes live in the WordPress directory tomorrow and we don't need any surprises. Thank you everyone who has contributed code or time to this version you efforts are greatly appreciated.

**Comment by vburlak** [comment]
excellent, @valendesigns  thanks :)

**Comment by valendesigns** [comment]
It's officially live in the WP Plugins directory. Thank you everyone for contributing!

**Comment by vburlak** [comment]
@valendesigns please, index package at https://packagist.org/packages/valendesigns/option-tree
the new version is not yet available with Composer

**Comment by valendesigns** [comment]
@vburlak Unfortunately, @BassemN created the package archive and needs to add me as an admin. I can't do anything about it right this moment.

**Comment by vburlak** [comment]
@BassemN your turn :)

**Comment by BassemN** [comment]
@valendesigns I added you as the maintainer of option-tree at packagist

**Comment by valendesigns** [comment]
@BassemN Perfect, thanks!

**Pull request merged**
