### PR TITLE
Filter on/off field choices

### PR DESCRIPTION
**Pull request by BassemN**
Add ability to filter on/off field choices

### CODE REVIEW

**Comment by valendesigns** [comment]
@BassemN Could you please give me more information on what scenarios you tested for? In your current implementation it seems like it would be to broad of a filter. I would think filtering the label for each choice is a better approach, but giving access to filter the entire array would likely end in a lot of misuse. What happens when there are more than two choices, does it still work and properly select the item and how about the styles? 

I think something like the following code would make it more extensible, but not break anything. You could also filter both the labels with a single function because of the second parameter passing the value.
```PHP
// Force choices & filter labels
$field_choices = array(
 array(
   'value'   => 'on',
   'label'   => apply_filters( 'ot_recognized_on_label', __( 'On', 'option-tree' ), $field_id, 'on' )
  ),
 array(
   'value'   => 'off',
   'label'   => apply_filters( 'ot_recognized_off_label', __( 'Off', 'option-tree' ), $field_id, 'off' )
 )
);
```

If the value could also be filtered, then we could add that, as well. But I think more testing is needed before I would be satisfied it's not going to break easily.

It could be adding into 2.5.0 if you have time to discuss this PR and make any discussed changes in the next day or so. Talk soon.

Cheers!

**Comment by BassemN** [comment]
@valendesigns  Filtering the entire array may cause a lot of misuse so I filtered the label and value for each choice.

**Comment by valendesigns** [comment]
Did you test that it works when you change the value?

**Comment by BassemN** [comment]
Yes, I tested it on my localhost and it is working without any problems.

**Comment by valendesigns** [comment]
Thank you for making the changes. Unfortunately, as it was I found a couple use cases where things fall apart and I had to make some modifications for everything to work properly. Specifically when labels are long. I've merged your updates into a new branch where I've documented and renamed the filters, plus added a new filter that allows the width of the switch to be changed and made the inner elements percentage based. Please check out PR #447 and test & comment there going forward.

**Pull request closed without merging**
