### PR TITLE
Fixed php7 notice. Same as in commit d26b348.

### PR DESCRIPTION
**Pull request by primozcigler**
`Notice: Only variables should be passed by reference in ot-loader.php on
line 329.`

bug

### CODE REVIEW

**Comment by primozcigler** [comment]
@valendesigns can this be merged please?

**Comment by eimanavicius** [comment]
@valendesigns I'm waiting for this fix too.

**Comment by m-aciek** [comment]
To have it mentioned: change same as in #592, which is already merged.

**Comment by anteksiler** [comment]
@valendesigns Hi Derek, could you please merge this? :)

**Comment by primozcigler** [comment]
@valendesigns I understand that it is hard to be a maintainer of the open source project, but if you agree I volunteer to help you with merging at least pull request if you add me as a maintainer of this repo.

**Comment by Xairoo** [comment]
+1

**Comment by ryanlabelle** [comment]
+1 :) If you can merge please.

**Comment by pabagan** [comment]
+1

**Comment by icookcode** [comment]
I'm still getting this error and it's 2018 now.

**Comment by valendesigns** [comment]
Fixed in #695

**Pull request closed without merging**
