### PR TITLE
Estonian translation

### PR DESCRIPTION
**Pull request by RistoNiinemets**
Fully translated Option-Tree into Estonian. Most of the work has been done by @tjuris.

### CODE REVIEW

**Comment by valendesigns** [comment]
Could either of you guys refresh this pull request by pulling in changes from the `feature-google-font` branch and updating the included `.po` & `.mo` files so it can merged into 2.5.0 cleanly? That would be a big help. You don't need to update all the new stings, unless you want to, but getting it prepared for the next release will insure it gets included. Also, thank you for doing this work and sorry for how long it's been sitting here.

**Comment by RistoNiinemets** [comment]
Thanks! I refreshed it, but we will need to update the translations. We will try to make it quickly :)

**Comment by RistoNiinemets** [comment]
@valendesigns translation complete, props @tjuris

**Comment by valendesigns** [comment]
Thank you both of you for your contributions. One last thing. This PR is trying to merge into `master` it should `release-2.5.0`.

**Comment by valendesigns** [comment]
Actually, disregard my last comment. I can just merge it the old fashioned way. Thanks again!

**Comment by valendesigns** [comment]
I've merged this into the google font branch as the last bits get worked out.

**Comment by valendesigns** [comment]
@RistoNiinemets Could you please translate the 2 new strings in PR #410? They're fairly short.

**Pull request closed without merging**
